export const timeZones = [
  { label: "UTC (Universal Time Coordinated)", ianaName: "UTC" },
  { label: "EST (Eastern Standard Time)", ianaName: "America/New_York" },
  { label: "CST (Central Standard Time)", ianaName: "America/Chicago" },
  { label: "MST (Mountain Standard Time)", ianaName: "America/Denver" },
  { label: "PST (Pacific Standard Time)", ianaName: "America/Los_Angeles" },
  { label: "GMT (Greenwich Mean Time)", ianaName: "Europe/London" },
  { label: "BST (British Summer Time)", ianaName: "Europe/London" },
  { label: "CET (Central European Time)", ianaName: "Europe/Paris" },
  { label: "IST (Israel Standard Time)", ianaName: "Asia/Jerusalem" },
  { label: "AST (Arabian Standard Time)", ianaName: "Asia/Riyadh" },
  { label: "IST (India Standard Time)", ianaName: "Asia/Kolkata" },
  { label: "CST (China Standard Time)", ianaName: "Asia/Shanghai" },
  { label: "JST (Japan Standard Time)", ianaName: "Asia/Tokyo" },
];
